### ISSUE TITLE
[Issue] 수정 및 보완할 점 제안

### ISSUE THREAD

**Issue by chanwoong1** [42ft-transcendence/mini_project_auth_chat#19]
1. 회원 정보 삭제 기능 추가

현재 인증 완료 후 회원가입 페이지에 들어왔을 때, 과거에 설정한 닉네임이 있을 경우 닉네임이 유지가 되고 있는것을 확인할 수 있습니다.

<img width="502" alt="스크린샷 2023-07-26 오전 2 33 07" src="https://github.com/42ft-transcendence/mini_project_auth_chat/assets/84218652/3b5e8446-5acc-47ed-8100-704d7e24b473">

취소 버튼이나, 에러, 브라우저 종료 등 회원가입 페이지 내부에서 확인 버튼을 제외한 여러 동작들이 발생할 경우, 생성된 유저 데이터를 지워주어야 하겠습니다.

**Comment by Park-Jeong-Ki** [comment]
@chanwoong1 완료 했습니다!
